
# GitHub funding configuration
# This file enables sponsorship for the project

# List GitHub usernames here if you want to enable GitHub Sponsors
# github: [yourusername]

# List your other funding platforms
# patreon: yourusername
# open_collective: yourproject
# ko_fi: yourusername
# tidelift: npm/package-name
# community_bridge: yourproject
# liberapay: yourusername
# issuehunt: yourusername
# otechie: yourusername
# lfx_crowdfunding: yourproject
# custom: ['https://your-website.com/donate']
